---
output: 
  pdf_document:
    latex_engine: xelatex
papersize: letter
mainfont: Verdana
header-includes:
- \usepackage[fontsize=12pt]{scrextend}  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, cache = FALSE, dev = "cairo_pdf")

library(dplyr) # data munging
library(envreportutils) # order_df
library(lubridate)
library(tidyr) # reshape df
library(scales) # percent()
library(tibble) # rownames_to_column()
library(ggplot2)
library(envreportutils) # theme_soe()
library(stringr) # for label wrapping

knitr::read_chunk("03_output.R")

## Load clean data if not already in local repository
if (!exists("virtual_clean")) load("tmp/trans_gwlic_clean.RData")
```


```{r pre}
```
<!--\pagenumbering{gobble}-->


# B.C. Groundwater Licensing Transition Project

\vspace{12pt}

# STATUS as of `r ddate`

Data sourced from FLNRO e-Licensing system accessed on `r ddate`

\vspace{32pt}

```{r estimate, fig.height = 2, fig.width = 7}

```

<!--
\vspace{32pt}

```{r stage_rates, fig.height = 4, fig.width = 7}

```

\vspace{24pt}

-->



\vspace{32pt}

## FrontCounter BC: Current Applications in Processing  

\vspace{12pt}
  
```{r virtual_status, fig.height = 2, fig.width = 7}

```

<!--

```{r app_rate, fig.height = 4, fig.width = 7}

```

-->


## FLNRO E-Licensing: Applications Under Adjudication 

\vspace{12pt}

```{r elic_status, fig.height = 2, fig.width = 7}

```

\vspace{14pt}

```{r elic_regions, fig.height = 5, fig.width = 7}

```


```{r water_use, fig.height = 6, fig.width = 7}

```

